### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by eunseo5355** [29th-WE-SOPT-iOS-Part/BaeEunSeo#10]
## 📌  Feature Issue

로그인과 회원가입에 실제 API 붙여보기

## 📝  To-do

▶️ 화면 전환하기
- [x] 유튜브 홈 화면을 시작 화면으로 설정한 후 계정 프로필을 클릭 시 로그인 화면이 뜨도록 구현하기

▶️ 서버 통신하기
- [x] 로그인 화면에서 다음 버튼을 누르면 서버 통신하고 alert 띄우기
- [x] 회원가입 화면에서 다음 버튼을 누르면 서버 통신하고 alert 띄우기

▶️ 도전과제
- [x] 로그인 시 서버와 통신 후 받은 name 값을 UserDefault에 저장한 후 확인 화면에 name 띄우기
